services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scrabble
    ports:
      - "6306:3306"

  php:
    build: ./docker/php
    volumes:
      - ./:/application:cached
    depends_on:
      - mysql
      # - mailhog
      # - redis

  php_xdebug:
    build:
      context: ./docker/php
      args:
        - xdebug=1
    volumes:
      - ./:/application:cached
    depends_on:
      - mysql
      # - mailhog
      # - redis

  nginx:
    image: nginx
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - php
      - php_xdebug

  node:
    image: node
    volumes:
      - .:/application:cached
    working_dir: /application
    command: "tail -f /dev/null"

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025"

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

version: '3'
